// =============================
// docs/map/map.js
// 
// Type this in the terminal: `node docs/map/map.js`
// =============================

import fs from "fs";
import path from "path";

// ===== Settings =====
const outputMapPath = "docs/map/context-map.md";
const IGNORE_EXT = [];
const EXCEPTION_NAMES = ["README.md", "robots.txt"];
const IGNORE_HIDDEN_FILES = true;

const MAP_DESCRIPTION = `# Project Context Map 

## Description
\`${outputMapPath}\`: A generated file that provides a visual representation of the project's directory structure. It is intended to help developers and contributors understand the organization of the project and locate files more easily. The map is generated by traversing the project directory and listing all files and folders, while respecting .gitignore rules and other specified ignore settings.
\nThe map is useful for quickly identifying the layout of the project, understanding the relationships between different components, and navigating the codebase. It can also serve as a reference for new contributors to get acquainted with the project's structure.`;

// Binary extensions – never read for LOC counting and excluded from the main summary
const BINARY_EXTENSIONS = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico",
  ".mp4", ".webm", ".avi", ".mov", ".mp3", ".wav",
  ".pdf", ".zip", ".tar", ".gz", ".rar", ".7z",
  ".exe", ".dll", ".so", ".dylib", ".bin", ".dat",
  ".db", ".sqlite", ".ttf", ".woff", ".woff2", ".eot", ".otf",
  ".svg"
]);

// Lockfiles – skip LOC counting but keep in tree and include in code summary (with 0 LOC)
const LOCKFILES = new Set([
  "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "composer.lock"
]);

// ===== Determine paths =====
const scriptDir = import.meta.dirname;
const rootDir = path.resolve(scriptDir, "../../");
const outputFile = path.join(rootDir, outputMapPath);

// ===== Parse .gitignore =====
function getGitignoreRules() {
  const gitignorePath = path.join(rootDir, ".gitignore");
  const rules = [/(^|\/)\.git($|\/)/];

  if (fs.existsSync(gitignorePath)) {
    const lines = fs.readFileSync(gitignorePath, "utf-8").split("\n");
    for (let line of lines) {
      line = line.trim();
      if (!line || line.startsWith("#")) continue;

      let escaped = line.replace(/[.+^${}()|[\]\\]/g, "\\$&");
      escaped = escaped.replace(/\*/g, ".*").replace(/\?/g, ".");

      if (escaped.startsWith("\\/")) {
        rules.push(new RegExp("^" + escaped.substring(2) + "($|/)"));
      } else {
        rules.push(new RegExp("(^|/)" + escaped + "($|/)"));
      }
    }
  }
  return rules;
}

const ignoreRegexes = getGitignoreRules();

function isIgnored(itemPath, isDir, itemName) {
  if (EXCEPTION_NAMES.includes(itemName)) return false;
  if (IGNORE_HIDDEN_FILES && itemName.startsWith(".")) return true;
  if (IGNORE_EXT.some((ext) => itemName.endsWith(ext))) return true;

  const relativePath = path.relative(rootDir, itemPath).replace(/\\/g, "/");
  return ignoreRegexes.some((regex) => regex.test(relativePath) || (isDir && regex.test(relativePath + "/")));
}

// ===== Main generation =====
function generateTree() {
  const outputDir = path.dirname(outputFile);
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const outputStream = fs.createWriteStream(outputFile, { encoding: "utf-8" });

  // Write header (outside code block)
  if (MAP_DESCRIPTION && MAP_DESCRIPTION.trim()) {
    outputStream.write(`${MAP_DESCRIPTION.trim()}\n\n`);
  }

  // Open code block for the tree
  outputStream.write("## Map of Project Structure\n\n");
  outputStream.write("```text\n");
  outputStream.write(`${path.basename(rootDir)}/\n`);

  // Statistics
  const stats = {
    totalFiles: 0,
    extensions: {} // ext -> { count, loc }
  };

  function countLOC(filePath) {
    const ext = path.extname(filePath);
    const name = path.basename(filePath);

    if (BINARY_EXTENSIONS.has(ext)) return 0;
    if (LOCKFILES.has(name)) return 0;

    try {
      const content = fs.readFileSync(filePath, "utf-8");
      return content.split("\n").length;
    } catch {
      return 0;
    }
  }

  function walkDir(currentPath, prefix = "") {
    let allItems = fs.readdirSync(currentPath);
    const files = [];
    const dirs = [];

    allItems.forEach((item) => {
      if (item === ".git") return;
      const fullPath = path.join(currentPath, item);
      const isDir = fs.statSync(fullPath).isDirectory();
      if (isIgnored(fullPath, isDir, item)) return;
      if (isDir) dirs.push(item);
      else files.push(item);
    });

    files.sort();
    dirs.sort();

    // Root: files first; everywhere else: directories first
    let sortedItems;
    if (currentPath === rootDir) {
      sortedItems = [...files, ...dirs];
    } else {
      sortedItems = [...dirs, ...files];
    }

    for (let i = 0; i < sortedItems.length; i++) {
      const item = sortedItems[i];
      const isLast = i === sortedItems.length - 1;
      const connector = isLast ? "└── " : "├── ";
      const fullPath = path.join(currentPath, item);
      const isDir = fs.statSync(fullPath).isDirectory();

      outputStream.write(`${prefix}${connector}${item}${isDir ? "/" : ""}\n`);

      if (isDir) {
        const newPrefix = prefix + (isLast ? "    " : "│   ");
        walkDir(fullPath, newPrefix);

        // Insert a blank line after this directory's subtree if there are more siblings
        if (!isLast) {
          if (prefix === "") {
            // Root level: just a pipe to continue the tree
            outputStream.write("│\n");
          } else {
            // Deeper level: use the child prefix (which includes all pipes)
            outputStream.write(newPrefix + "\n");
          }
        }
      } else {
        // File – gather stats
        stats.totalFiles++;
        const ext = path.extname(item) || "(no extension)";
        if (!stats.extensions[ext]) {
          stats.extensions[ext] = { count: 0, loc: 0 };
        }
        stats.extensions[ext].count++;
        const loc = countLOC(fullPath);
        stats.extensions[ext].loc += loc;
      }
    }
  }

  walkDir(rootDir);

  // Close code block
  outputStream.write("```\n\n");

  // ----- Write summary -----
  outputStream.write("## Codebase Summary\n\n");

  const codeExtensions = {};
  const binaryExtensions = {};
  let codeTotalFiles = 0;
  let binaryTotalFiles = 0;
  let totalLoc = 0;

  for (const [ext, data] of Object.entries(stats.extensions)) {
    if (BINARY_EXTENSIONS.has(ext)) {
      binaryExtensions[ext] = data;
      binaryTotalFiles += data.count;
    } else {
      codeExtensions[ext] = data;
      codeTotalFiles += data.count;
      totalLoc += data.loc;
    }
  }

  // Code table
  const sortedCode = Object.entries(codeExtensions).sort((a, b) => b[1].count - a[1].count);
  if (sortedCode.length > 0) {
    outputStream.write("### Code Files\n\n");
    outputStream.write("| Extension | Files | Lines of Code |\n");
    outputStream.write("|-----------|-------|---------------|\n");
    for (const [ext, data] of sortedCode) {
      outputStream.write(`| ${ext} | ${data.count} | ${data.loc} |\n`);
    }
    outputStream.write(`| **Total** | **${codeTotalFiles}** | **${totalLoc}** |\n\n`);
  }

  // Binary table
  const sortedBinary = Object.entries(binaryExtensions).sort((a, b) => b[1].count - a[1].count);
  if (sortedBinary.length > 0) {
    outputStream.write("### Binary / Media Files\n\n");
    outputStream.write("| Extension | Files |\n");
    outputStream.write("|-----------|-------|\n");
    for (const [ext, data] of sortedBinary) {
      outputStream.write(`| ${ext} | ${data.count} |\n`);
    }
    outputStream.write(`| **Total** | **${binaryTotalFiles}** |\n\n`);
  }

  outputStream.write(`**Grand Total Files:** ${stats.totalFiles}  \n`);
  outputStream.write(`**Total Lines of Code (code files only):** ${totalLoc}\n`);

  outputStream.end();

  const relativeOutput = path.relative(rootDir, outputFile);
  console.log(`Done! Check: ${relativeOutput}`);
}

generateTree();
